### ISSUE TITLE
Dataset not downloading train.lst or associated files

### ISSUE THREAD

**Issue by NelBlue** [AutodeskAILab/Clip-Forge#4]
```
2022-06-19 12:44:31,178 - INFO - #############################
{'__pycache__': 0}
{'__pycache__': {'id': '__pycache__', 'name': 'n/a'}}
Traceback (most recent call last):
  File "train_autoencoder.py", line 383, in <module>
    main()   
  File "train_autoencoder.py", line 316, in main
    train_dataloader, total_shapes  = get_dataloader(args, split="train")
  File "train_autoencoder.py", line 105, in get_dataloader
    dataset = shapenet_dataset.Shapes3dDataset(args.dataset_path, fields, split=split,
  File "/home/yboutros/repos/MeshGen/zeroshot/AudodeskAILab/Clip-Forge/dataset/shapenet_dataset.py", line 409, in __init__
    with open(split_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/__pycache__/train.lst'
```
So, I should probably be doing this in Conda, if this continues to fail ill just set that up, but what kind of data is train.lst looking for? Looking at other repos it seems train.lst is justa txt file associating input datapaths with output datapaths. I downloaded the exps folder in the usage but all the subfolders are empty

**Comment by sanghiad** [comment]
@NelBlue did you install the dataset from occupancy network repo? I believe this is the training split text file.
